apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2021-01-07T10:19:20Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:release.openshift.io/create-only: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2021-01-07T10:19:20Z"
  name: cluster
  resourceVersion: "1821"
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: 2b3644db-d9b3-433c-8c04-0c3cfbcff9bb
spec: 
  identityProviders:
  - htpasswd:
       fileData:
          name: passwords
    type:	HTPasswd
    name: local
