apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: quotes-template
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: quotedb
        app.kubernetes.io/component: quotedb
        app.kubernetes.io/instance: quotedb
        app.kubernetes.io/name: mysql
      name: quotedb
      namespace: quotes
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: quotedb
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deploymentconfig: quotedb
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      key: database
                      name: env
                - name: MYSQL_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: name
                      name: env
                - name: MYSQL_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      key: password
                      name: env
                - name: MYSQL_USER
                  valueFrom:
                    configMapKeyRef:
                      key: user
                      name: env
              imagePullPolicy: IfNotPresent
              name: quotedb
              ports:
                - containerPort: 3306
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - quotedb
            from:
              kind: ImageStreamTag
              name: mysql:5.7
              namespace: openshift
          type: ImageChange
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: quotes
        app.kubernetes.io/component: quotes
        app.kubernetes.io/instance: quotes
      name: quotes
      namespace: quotes
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: quotes
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deploymentconfig: quotes
        spec:
          containers:
            - env:
                - name: DATABASE_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: name
                      name: env
                - name: DATABASE_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      key: password
                      name: env
                - name: DATABASE_USER
                  valueFrom:
                    configMapKeyRef:
                      key: user
                      name: env
                - name: DATABASE_SERVICE_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: service_name
                      name: env
                - name: DATABASE_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      key: database
                      name: env
              imagePullPolicy: Always
              name: quotes
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - quotes
            from:
              kind: ImageStreamTag
              name: quotes:latest
              namespace: quotes
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: "2021-02-05T20:50:14Z"
      labels:
        app: quotedb
        app.kubernetes.io/component: quotedb
        app.kubernetes.io/instance: quotedb
        app.kubernetes.io/name: mysql
      name: quotedb
      namespace: quotes
    spec:
      ports:
        - name: 3306-tcp
          port: 3306
          protocol: TCP
          targetPort: 3306
      selector:
        deploymentconfig: quotedb
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: "2021-02-05T20:52:34Z"
      labels:
        app: quotes
        app.kubernetes.io/component: quotes
        app.kubernetes.io/instance: quotes
      name: quotes
      namespace: quotes
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        deploymentconfig: quotes
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: "2021-02-05T20:50:18Z"
      name: quotedb
      namespace: quotes
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
          importPolicy: {}
          name: "5.7"
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: "2021-02-05T20:52:34Z"
      labels:
        app: quotes
        app.kubernetes.io/component: quotes
        app.kubernetes.io/instance: quotes
      name: quotes
      namespace: quotes
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: "2021-02-05T20:52:34Z"
      labels:
        app: quotes
        app.kubernetes.io/component: quotes
        app.kubernetes.io/instance: quotes
      name: quotes
      namespace: quotes
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: quotes:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: quotes
        git:
          uri: https://github.com/mazmarz/DO288-apps-v1.git
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: php:7.3
            namespace: openshift
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: 7bpYAEhCUjOfkxs-WnpO
          type: GitHub
        - generic:
            secret: I5YPen2i74DLHToX5NU_
          type: Generic
        - type: ConfigChange
        - type: ImageChange
  - apiVersion: v1
    data:
      database: quotes
      name: quotes
      password: mypass
      server_name: quotedb
      service_name: quotedb
      user: appuser
    kind: ConfigMap
    metadata:
      name: env
      namespace: quotes
